import assert from 'node:assert/strict';
import { createHash, randomBytes } from 'node:crypto';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer as reserveServer } from 'node:net';
import test from 'node:test';
import { Result } from 'better-result';
import { CodexBridge } from './codex-bridge.js';
import type { LocalAgentRecord } from './local-agent-store.js';
import { OwnerApprovals, classifyMcpOperation } from './mcp-authorization.js';
import { createServer } from './server.js';
import { loadConfig } from './config.js';
import { writeTestDevspaceConfig } from './test-support/config.test.js';

const owner = 'fixture-only-owner-password-long-enough';
const operation = { principal: 'client:session', tool: 'exec_command', args: { cmd: 'echo ok' }, context: { root: 'fixture' }, reason: 'shell' };
test('Chat approval requires a private UI capability bound to the exact principal and request', () => {
  let now = 0; const store = new OwnerApprovals(() => now, 100);
  const pending = store.require(operation); if (pending.allowed) throw Error('unexpected');
  const id = pending.approval.id;
  const view = store.reviewUi(id, operation.principal);
  assert.ok(view.decisionToken);
  assert.throws(() => store.reviewUi(id, 'other-client'), /unavailable/);
  assert.throws(() => store.decideUi(id, operation.principal, 'forged', true), /unavailable/);
  assert.throws(() => store.decideUi(id, 'other-conversation', view.decisionToken!, true), /unavailable/);
  assert.equal(store.inspect(id)?.state, 'pending');
  const other = store.require({ ...operation, args: { cmd: 'different' } }); if (other.allowed) throw Error('unexpected');
  assert.throws(() => store.decideUi(other.approval.id, operation.principal, view.decisionToken!, true), /unavailable/);
  const decided = store.decideUi(id, operation.principal, view.decisionToken!, true);
  assert.equal(decided.state, 'approved');
  assert.equal(store.decideUi(id, operation.principal, view.decisionToken!, false).state, 'approved', 'decision replay cannot change the outcome');
  assert.equal(store.require(operation).allowed, true);
  assert.equal(store.require(operation).allowed, false, 'UI approval remains single-use');
  now = 101;
  assert.throws(() => store.reviewUi(other.approval.id, operation.principal), /unavailable/);
});

test('Codex approval submits once without a Chat retry and retains a scoped receipt', async () => {
  const store = new OwnerApprovals(); let calls = 0;
  const task = { ...operation, tool: 'codex_task_start', args: { workspaceId: 'ws-fixture', requestKey: 'one', prompt: 'read only' } };
  const request = store.require(task, async () => { calls++; return { agentId: 'agt-fixture', workspaceId: 'ws-fixture' }; });
  if (request.allowed) throw Error('unexpected');
  const id = request.approval.id, nonce = store.challenge(id);
  assert.equal(calls, 0);
  assert.equal(store.decide(id, nonce, 'wrong', owner, true), false);
  assert.equal(calls, 0);
  assert.equal(store.decide(id, nonce, owner, owner, true), true);
  assert.equal(store.decide(id, nonce, owner, owner, true), false);
  await new Promise<void>(resolve => setImmediate(resolve));
  assert.equal(calls, 1, 'Owner approval must dispatch without another MCP call');
  const replay = store.require(task); if (replay.allowed) throw Error('must return receipt, not a second execution grant');
  assert.equal(replay.approval.state, 'submitted');
  assert.deepEqual(replay.approval.submission, { agentId: 'agt-fixture', workspaceId: 'ws-fixture' });
  assert.equal(calls, 1);
  for (const changed of [{ ...task, principal: 'another-client' }, { ...task, args: { ...task.args, prompt: 'changed' } }, { ...task, context: { root: 'elsewhere' } }]) {
    const denied = store.require(changed); if (denied.allowed) throw Error('unexpected');
    assert.equal(denied.approval.state, 'pending');
  }
});

test('automatic submission is fail-closed on denial, expiry, shutdown and failure', async () => {
  let now = 0, calls = 0; const store = new OwnerApprovals(() => now, 100);
  const task = { ...operation, tool: 'codex_task_continue' };
  const submit = async () => { calls++; throw Error('fixture submission failure'); };
  const request = store.require(task, submit); if (request.allowed) throw Error('unexpected');
  const id = request.approval.id;
  assert.equal(store.decide(id, store.challenge(id), owner, owner, false), true);
  assert.equal(calls, 0);
  store.clear();
  const expired = store.require(task, submit); if (expired.allowed) throw Error('unexpected');
  const nonce = store.challenge(expired.approval.id); now = 101;
  assert.equal(store.decide(expired.approval.id, nonce, owner, owner, true), false);
  assert.equal(calls, 0);
  const failed = store.require(task, submit); if (failed.allowed) throw Error('unexpected');
  store.decide(failed.approval.id, store.challenge(failed.approval.id), owner, owner, true);
  await new Promise<void>(resolve => setImmediate(resolve));
  assert.equal(calls, 1); assert.equal(store.inspect(failed.approval.id)?.state, 'failed');
  store.require(task, submit); assert.equal(calls, 1, 'failed delivery must not automatically retry');
  await store.close();
  assert.throws(() => store.require(task, submit), /closed/);
});

test('approval is principal/argument/context bound, single-use, bounded and fail-closed', () => {
  let now = 0; const store = new OwnerApprovals(() => now, 100);
  const pending = store.require(operation); assert.equal(pending.allowed, false); if (pending.allowed) return;
  const id = pending.approval.id, nonce = store.challenge(id);
  assert.equal(store.decide(id, 'forged', owner, owner, true), false);
  assert.equal(store.decide(id, nonce, 'wrong', owner, true), false);
  assert.equal(store.decide(id, nonce, owner, owner, true), true);
  assert.equal(store.require({ ...operation, principal: 'other' }).allowed, false);
  assert.equal(store.require({ ...operation, args: { cmd: 'different' } }).allowed, false);
  assert.equal(store.require({ ...operation, context: { root: 'changed' } }).allowed, false);
  assert.equal(store.require(operation).allowed, true);
  assert.equal(store.require(operation).allowed, false);
  now = 101; assert.equal(store.inspect(id), undefined);
  const request = store.require(operation); if (request.allowed) throw Error('unexpected');
  assert.equal(store.decide(request.approval.id, store.challenge(request.approval.id), owner, owner, false), true);
  const denied = store.require(operation); assert.equal(denied.allowed, false);
  if (!denied.allowed) assert.equal(denied.approval.state, 'denied');
  store.clear(); assert.equal(store.require(operation).allowed, false);
  for (let i=0;i<19;i++) store.require({ ...operation, args: { cmd: String(i) } });
  assert.throws(() => store.require({ ...operation, args: { cmd: 'overflow' } }), /Too many/);
});

test('real OAuth/MCP requires independent Owner approval before command side effects', { timeout: 60000 }, async t => {
  const root = mkdtempSync(join(tmpdir(), 'devspace-owner-http-'));
  const project = join(root, 'project'); mkdirSync(project);
  writeFileSync(join(project,'hello.txt'),'hello\n');
  const reserve = reserveServer(); await new Promise<void>(r => reserve.listen(0, '127.0.0.1', r));
  const port = (reserve.address() as {port:number}).port; await new Promise<void>(r => reserve.close(() => r()));
  const origin = `http://127.0.0.1:${port}`, resource = `${origin}/mcp`;
  const config = loadConfig({ ...writeTestDevspaceConfig(join(root,'config'), {
    server: { port, publicBaseUrl: origin }, workspaces: { allowedRoots: [project] },
    storage: { stateDir: join(root,'state') }, skills: { enabled: false }, tools: { authorization: 'owner_approval', approvalTtlSeconds: 7200 },
    logging: { level: 'silent' },
  }), DEVSPACE_OAUTH_OWNER_TOKEN: owner });
  const noWorkspace = { getWorkspace:()=>{throw Error('not needed');}, resolveReadPath:()=>{throw Error('not needed');} };
  assert.ok(classifyMcpOperation(config,noWorkspace,'codex_task_start',{writeMode:'read_only',prompt:'read protected files'}).reason);
  assert.ok(classifyMcpOperation(config,noWorkspace,'show_changes',{}).reason);
  const policy = { requiredModel: 'gpt-6-astra', minimumCliVersion: '0.153.0', allowedModels: ['gpt-6-astra', 'gpt-5.6-sol'], routing: { routineModel: 'gpt-5.6-sol', complexModel: 'gpt-6-astra' } };
  config.bridge = { enabled: true, allowWorkspaceWrite: false, executionPolicy: policy };
  const submissions: any[] = [];
  const record: LocalAgentRecord = { id: 'agt-owner-fixture', workspaceRoot: project, profileName: 'codex', provider: 'codex', model: 'gpt-5.6-sol', status: 'running', createdAt: 'now', updatedAt: 'now' };
  const app = createServer(config, { codexBridgeFactory: configuration => new CodexBridge(configuration, {
    start: async input => { submissions.push(input); return Result.ok(record); },
    continue: async (agentId, prompt, overrides) => { submissions.push({ agentId, prompt, ...overrides }); return Result.ok(record); },
    get: async () => Result.ok(record), list: async () => Result.ok([]),
  }, () => ({ executable: 'fixture-cli-not-launched', version: '0.153.4' })) });
  const listener = app.app.listen(port,'127.0.0.1'); await new Promise<void>(r => listener.once('listening', r));
  t.after(async () => { await app.close(); listener.closeAllConnections(); await new Promise<void>(r => listener.close(() => r())); rmSync(root, {recursive:true,force:true}); });
  const clientIds = new Map<string, string>();
  const login = async (name:string) => {
    const registration = await fetch(`${origin}/register`, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({
      client_name:name, redirect_uris:['http://127.0.0.1/callback'], token_endpoint_auth_method:'none', grant_types:['authorization_code','refresh_token'], response_types:['code'],
    }) });
    assert.equal(registration.status,201); const client = await registration.json() as {client_id:string};
    const verifier = randomBytes(32).toString('base64url');
    const params = { client_id:client.client_id, redirect_uri:'http://127.0.0.1/callback', response_type:'code', scope:'devspace', resource,
      code_challenge:createHash('sha256').update(verifier).digest('base64url'), code_challenge_method:'S256' };
    const authorize = await fetch(`${origin}/authorize`, { method:'POST', redirect:'manual', body:new URLSearchParams({...params,owner_token:owner}) });
    assert.equal(authorize.status,302); const code = new URL(authorize.headers.get('location')!).searchParams.get('code')!;
    const exchanged = await fetch(`${origin}/token`, {method:'POST',body:new URLSearchParams({grant_type:'authorization_code',client_id:client.client_id,code,code_verifier:verifier,redirect_uri:params.redirect_uri,resource})});
    assert.equal(exchanged.status,200);
    const accessToken = (await exchanged.json() as {access_token:string}).access_token;
    clientIds.set(accessToken, client.client_id); return accessToken;
  };
  const access = await login('Owner gate fixture');
  let session='', id=0;
  const rpc = async (method:string, params:unknown, bearer=access) => {
    const response = await fetch(resource, {method:'POST',headers:{authorization:`Bearer ${bearer}`,'content-type':'application/json',accept:'application/json, text/event-stream',...(session?{'mcp-session-id':session}:{})},body:JSON.stringify({jsonrpc:'2.0',id:++id,method,params})});
    session = response.headers.get('mcp-session-id') ?? session;
    const text = await response.text();
    assert.equal(response.status,200,text);
    return JSON.parse(text.startsWith('event:') ? text.split('\n').find(line=>line.startsWith('data:'))!.slice(5) : text);
  };
  await rpc('initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'fixture',version:'1'}});
  const opened=await rpc('tools/call',{name:'open_workspace',arguments:{path:project}});
  const workspaceId=opened.result.structuredContent.workspaceId; assert.ok(workspaceId);
  const conversationMeta={'openai/session':'fixture-logical-chat'};
  const tool=(name:string,args:Record<string,unknown>)=>rpc('tools/call',{name,arguments:{workspaceId,...args},_meta:conversationMeta});
  assert.notEqual((await tool('project_read',{path:'hello.txt'})).result.isError,true);
  assert.notEqual((await tool('project_read_batch', { items: [{ path: 'hello.txt' }] })).result.isError, true);
  writeFileSync(join(project, '.env'), 'FIXTURE_BATCH_SECRET_MUST_NOT_LEAK');
  const protectedBatch = await tool('project_read_batch', { items: [{ path: 'hello.txt' }, { path: '.env' }] });
  assert.equal(JSON.parse(protectedBatch.result.content[0].text).code, 'OWNER_APPROVAL_REQUIRED');
  assert.doesNotMatch(JSON.stringify(protectedBatch), /FIXTURE_BATCH_SECRET_MUST_NOT_LEAK/);
  const escapedBatch = await tool('project_read_batch', { items: [{ path: 'hello.txt' }, { path: '../outside.txt' }] });
  assert.equal(escapedBatch.result.isError, true);
  assert.equal(JSON.parse(escapedBatch.result.content[0].text).code, 'WORKSPACE_ACCESS_DENIED');
  const nativeBlocked = await tool('run_process', { executable: process.execPath,
    args: ['-e', "require('node:fs').writeFileSync('native-not-approved.txt','bad')"] });
  assert.equal(JSON.parse(nativeBlocked.result.content[0].text).code, 'OWNER_APPROVAL_REQUIRED');
  assert.equal(existsSync(join(project, 'native-not-approved.txt')), false);
  const cancelBlocked = await tool('process_cancel', { sessionId: 12345 });
  assert.equal(JSON.parse(cancelBlocked.result.content[0].text).code, 'OWNER_APPROVAL_REQUIRED');
  const absentStatus = await tool('process_status', { sessionId: 12345, yieldTimeMs: 0 });
  assert.equal(absentStatus.result.isError, true);
  assert.doesNotMatch(JSON.stringify(absentStatus), /OWNER_APPROVAL_REQUIRED/);
  const approvalStartedAt = Date.now();
  const args={cmd:'echo approved> approved.txt',yieldTimeMs:10000};
  const blocked=await tool('exec_command',args); assert.equal(blocked.result.isError,true);
  const approval=JSON.parse(blocked.result.content[0].text); assert.equal(approval.code,'OWNER_APPROVAL_REQUIRED');
  assert.ok(Date.parse(approval.expiresAt) >= approvalStartedAt + 7200_000);
  assert.ok(Date.parse(approval.expiresAt) <= Date.now() + 7200_000);
  assert.equal(existsSync(join(project,'approved.txt')),false);
  const forged=await tool('exec_command',{...args,approved:true}); assert.equal(forged.result.isError,true);
  const page=await fetch(approval.approvalUrl); const html=await page.text();
  const nonce=/name="nonce" value="([^"]+)"/.exec(html)![1], cookie=page.headers.get('set-cookie')!.split(';')[0];
  const decide=(originHeader:string|undefined,password:string,extraHeaders:Record<string,string>={})=>fetch(approval.approvalUrl,{method:'POST',headers:{...(originHeader===undefined?{}:{origin:originHeader}),cookie,...extraHeaders},body:new URLSearchParams({nonce,owner_token:password,decision:'approve'})});
  assert.equal((await decide('https://attacker.invalid',owner)).status,403);
  assert.equal((await decide('null',owner)).status,403);
  assert.equal((await decide(undefined,owner)).status,403);
  assert.equal((await decide('https://attacker.invalid',owner,{'x-forwarded-host':new URL(origin).host,'x-forwarded-proto':'http',referer:approval.approvalUrl})).status,403);
  assert.equal((await decide(origin,owner,{cookie:''})).status,403);
  assert.equal((await decide(origin,owner,{cookie:cookie.split('=')[0]+'=forged'})).status,403);
  assert.equal((await fetch(approval.approvalUrl,{method:'POST',headers:{origin,cookie},body:new URLSearchParams({nonce:'forged',owner_token:owner,decision:'approve'})})).status,403);
  assert.equal((await decide(origin,'wrong')).status,403);
  assert.equal((await decide(origin,owner)).status,200);
  assert.equal((await decide(origin,owner)).status,403,'a decided grant cannot be approved twice');
  assert.equal(existsSync(join(project,'approved.txt')),false,'approval alone must not execute');
  const otherClient = await login('Other OAuth client fixture');
  const otherAttempt = await rpc('tools/call',{name:'exec_command',arguments:{workspaceId,...args},_meta:conversationMeta},otherClient);
  assert.equal(JSON.parse(otherAttempt.result.content[0].text).code,'OWNER_APPROVAL_REQUIRED','another authenticated client cannot consume this grant');
  const otherConversation = await rpc('tools/call',{name:'exec_command',arguments:{workspaceId,...args},_meta:{'openai/session':'another-chat'}});
  assert.equal(JSON.parse(otherConversation.result.content[0].text).code,'OWNER_APPROVAL_REQUIRED','another logical conversation cannot consume this grant');
  session = '';
  await rpc('initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'fixture-reconnected',version:'1'}});
  assert.notEqual((await tool('exec_command',args)).result.isError,true,'the approved client must be able to retry after transport reconnection');
  assert.match(readFileSync(join(project,'approved.txt'),'utf8'),/approved/);
  assert.equal((await tool('exec_command',args)).result.isError,true,'grant must be consumed once');
  const patch='*** Begin Patch\n*** Update File: hello.txt\n@@\n-hello\n+updated\n*** End Patch';
  const expectedHashes={'hello.txt':createHash('sha256').update('hello\n').digest('hex')};
  assert.notEqual((await tool('apply_patch',{patch,expectedHashes})).result.isError,true);
  assert.equal(readFileSync(join(project,'hello.txt'),'utf8'),'updated\n');
  config.approvalProfile = 'high_risk_only';
  const automaticPatch = (before: string, after: string) => `*** Begin Patch\n*** Update File: hello.txt\n@@\n-${before}\n+${after}\n*** End Patch`;
  assert.notEqual((await tool('apply_patch', { patch: automaticPatch('updated', 'automatic') })).result.isError, true, 'ordinary patch does not request per-operation consent in the high-risk-only profile');
  assert.equal(readFileSync(join(project, 'hello.txt'), 'utf8'), 'automatic\n');
  assert.notEqual((await tool('apply_patch', { patch: automaticPatch('automatic', 'updated') })).result.isError, true);
  const protectedWrite = await tool('apply_patch', { patch: '*** Begin Patch\n*** Add File: package.json\n+{}\n*** End Patch' });
  assert.equal(JSON.parse(protectedWrite.result.content[0].text).code, 'OWNER_APPROVAL_REQUIRED');
  assert.equal(existsSync(join(project, 'package.json')), false);
  config.approvalProfile = 'conservative';
  const deletion=await tool('apply_patch',{patch:'*** Begin Patch\n*** Delete File: hello.txt\n*** End Patch',expectedHashes:{'hello.txt':createHash('sha256').update('updated\n').digest('hex')}});
  assert.equal(JSON.parse(deletion.result.content[0].text).code,'OWNER_APPROVAL_REQUIRED');
  assert.equal(existsSync(join(project,'hello.txt')),true);

  const approveTask = async (approvalUrl: string) => {
    const page = await fetch(approvalUrl), html = await page.text();
    assert.match(html, /Approving will automatically submit/);
    const nonce = /name="nonce" value="([^"]+)"/.exec(html)![1];
    const cookie = page.headers.get('set-cookie')!.split(';')[0];
    return fetch(approvalUrl, { method: 'POST', redirect: 'manual', headers: { origin, cookie },
      body: new URLSearchParams({ nonce, owner_token: owner, decision: 'approve' }) });
  };
  const taskArgs = { requestKey: 'owner-auto-one', prompt: ' '.repeat(4001) + 'Read hello.txt', model: ' auto ', writeMode: 'read_only' };
  const automatic = JSON.parse((await tool('codex_task_start', taskArgs)).result.content[0].text);
  assert.equal(automatic.executionMode, 'submit_on_approval'); assert.equal(submissions.length, 0);
  assert.equal((await approveTask(automatic.approvalUrl)).status, 303);
  for (let i = 0; i < 100 && !submissions.length; i++) await new Promise(resolve => setTimeout(resolve, 10));
  assert.equal(submissions.length, 1, 'human approval must submit without another tools/call');
  assert.equal(submissions[0].model, 'gpt-5.6-sol'); assert.equal(submissions[0].writeMode, 'read_only');
  assert.equal(submissions[0].prompt, 'Read hello.txt', 'review and execution must share schema normalization');
  const statusPage = await (await fetch(automatic.approvalUrl)).text();
  assert.match(statusPage, /Codex task submitted/); assert.match(statusPage, /agt-owner-fixture/);
  assert.doesNotMatch(statusPage, /owner_token|Read hello.txt/);
  session = '';
  await rpc('initialize',{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'auto-reconnected',version:'1'}});
  const receipt = await tool('codex_task_start', taskArgs);
  assert.notEqual(receipt.result.isError, true);
  assert.equal(JSON.parse(receipt.result.content[0].text).code, 'OWNER_OPERATION_SUBMITTED');
  assert.equal(JSON.parse(receipt.result.content[0].text).agentId, record.id);
  assert.equal(submissions.length, 1, 'old clients retrying after approval must not redeliver');
  const foreign = await rpc('tools/call',{name:'codex_task_start',arguments:{workspaceId,...taskArgs},_meta:conversationMeta},otherClient);
  assert.equal(JSON.parse(foreign.result.content[0].text).code,'OWNER_APPROVAL_REQUIRED');
  const foreignConversation = await rpc('tools/call',{name:'codex_task_start',arguments:{workspaceId,...taskArgs},_meta:{'openai/session':'foreign-chat'}});
  assert.equal(JSON.parse(foreignConversation.result.content[0].text).code,'OWNER_APPROVAL_REQUIRED');

  const followup = JSON.parse((await tool('codex_task_continue', { ...taskArgs, agentId: record.id, requestKey: 'followup' })).result.content[0].text);
  assert.equal((await approveTask(followup.approvalUrl)).status, 303);
  for (let i = 0; i < 100 && submissions.length < 2; i++) await new Promise(resolve => setTimeout(resolve, 10));
  assert.equal(submissions.length, 2); assert.equal(submissions[1].agentId, record.id);

  const changed = JSON.parse((await tool('codex_task_start', { ...taskArgs, requestKey: 'changed-model' })).result.content[0].text);
  policy.routing.routineModel = 'gpt-6-astra';
  await approveTask(changed.approvalUrl);
  await new Promise(resolve => setTimeout(resolve, 30));
  assert.match(await (await fetch(changed.approvalUrl)).text(), /Submission could not be confirmed/);
  assert.equal(submissions.length, 2, 'model changes after review invalidate automatic execution');
  policy.routing.routineModel = 'gpt-5.6-sol';

  const removedRoot = JSON.parse((await tool('codex_task_start', { ...taskArgs, requestKey: 'removed-root' })).result.content[0].text);
  config.allowedRoots = [];
  await approveTask(removedRoot.approvalUrl); await new Promise(resolve => setTimeout(resolve, 30));
  assert.match(await (await fetch(removedRoot.approvalUrl)).text(), /Submission could not be confirmed/);
  assert.equal(submissions.length, 2, 'workspace removal after review invalidates automatic execution');
  config.allowedRoots = [project];
  const cardArgs = { ...taskArgs, requestKey: 'chat-card-once' };
  const cardRequest = JSON.parse((await tool('codex_task_start', cardArgs)).result.content[0].text);
  assert.equal(cardRequest.chatApproval.enabled, false, 'Chat approval is opt-in for each authenticated OAuth client');
  assert.equal(cardRequest.chatApproval.clientId, clientIds.get(access));
  const reviewArgs = { name: 'review_approval', arguments: { approvalId: cardRequest.approvalId }, _meta: conversationMeta };
  assert.equal((await rpc('tools/call', reviewArgs)).result.isError, true);
  config.chatApprovalClientIds = [clientIds.get(access)!];
  const unscoped = await rpc('tools/call', { name: 'codex_task_start', arguments: { workspaceId, ...cardArgs, requestKey: 'unscoped-card' } });
  const unscopedId = JSON.parse(unscoped.result.content[0].text).approvalId;
  assert.equal(JSON.parse(unscoped.result.content[0].text).chatApproval.mode, 'owner_page');
  assert.equal(JSON.parse(unscoped.result.content[0].text).chatApproval.fallbackReason, 'CHAT_CONTEXT_REQUIRED');
  const unscopedReview = await rpc('tools/call', { name: 'review_approval', arguments: { approvalId: unscopedId } });
  assert.equal(unscopedReview.result.isError, true, 'Chat UI approval must not bind different conversations to a shared null scope');
  assert.equal(JSON.parse(unscopedReview.result.content[0].text).code, 'CHAT_CONTEXT_REQUIRED');
  const reviewed = await rpc('tools/call', reviewArgs);
  assert.notEqual(reviewed.result.isError, true);
  const view = reviewed.result._meta['devspace/approval'];
  assert.ok(view.decisionToken);
  const modelVisible = JSON.stringify({ content: reviewed.result.content, structuredContent: reviewed.result.structuredContent });
  assert.equal(modelVisible.includes(view.decisionToken), false);
  assert.equal(modelVisible.includes('decisionToken'), false);
  const listed = await rpc('tools/list', {});
  assert.deepEqual(listed.result.tools.find((item: any) => item.name === 'decide_approval')._meta.ui.visibility, ['app']);
  const uiDecision = { name: 'decide_approval', arguments: { approvalId: view.id, decisionToken: view.decisionToken, decision: 'approve' }, _meta: conversationMeta };
  const unreviewed = await rpc('tools/call', { name: 'decide_approval', arguments: { approvalId: view.id, decisionToken: 'forged', decision: 'approve' }, _meta: conversationMeta });
  assert.equal(unreviewed.result.isError, true);
  policy.routing.routineModel = 'gpt-6-astra';
  const staleReview = await rpc('tools/call', reviewArgs);
  assert.equal(staleReview.result.isError, true, 'stale model review must fail before consent');
  assert.equal(JSON.parse(staleReview.result.content[0].text).code, 'APPROVAL_CONTEXT_CHANGED');
  const staleDecision = await rpc('tools/call', uiDecision);
  assert.equal(staleDecision.result.isError, true, 'changed operation must not transition to approved');
  assert.equal(submissions.length, 2);
  policy.routing.routineModel = 'gpt-5.6-sol';
  assert.equal((await rpc('tools/call', { ...uiDecision, arguments: { ...uiDecision.arguments, decisionToken: 'forged' } })).result.isError, true);
  assert.equal((await rpc('tools/call', uiDecision, otherClient)).result.isError, true);
  assert.equal((await rpc('tools/call', { ...uiDecision, _meta: { 'openai/session': 'foreign-chat' } })).result.isError, true);
  assert.equal(submissions.length, 2);
  assert.notEqual((await rpc('tools/call', uiDecision)).result.isError, true);
  assert.notEqual((await rpc('tools/call', uiDecision)).result.isError, true, 'uncertain UI transport retries return the previous decision');
  for (let i = 0; i < 100 && submissions.length < 3; i++) await new Promise(resolve => setTimeout(resolve, 10));
  assert.equal(submissions.length, 3, 'a UI click triggers the existing one-turn submission exactly once');
  const cardReceipt = JSON.parse((await tool('codex_task_start', cardArgs)).result.content[0].text);
  assert.equal(cardReceipt.code, 'OWNER_OPERATION_SUBMITTED');
  assert.equal(submissions.length, 3);
  config.chatApprovalClientIds = [];
  assert.equal((await rpc('tools/call', reviewArgs)).result.isError, true, 'removing client trust revokes UI access immediately');
  const revoked = JSON.parse((await tool('codex_task_start', { ...taskArgs, requestKey: 'revoked-token' })).result.content[0].text);
  const revocation = await fetch(`${origin}/revoke`, { method: 'POST', body: new URLSearchParams({ token: access, client_id: clientIds.get(access)! }) });
  assert.equal(revocation.status, 200);
  await approveTask(revoked.approvalUrl); await new Promise(resolve => setTimeout(resolve, 30));
  assert.match(await (await fetch(revoked.approvalUrl)).text(), /Submission could not be confirmed/);
  assert.equal(submissions.length, 3, 'revoked OAuth credentials must not authorize deferred delivery');
});
